### ISSUE TITLE
Release changes from 2017

### ISSUE THREAD

**Issue by B3QL** [sorki/python-mnist#12]
Some of the available features still remain unreleased like:
- numpy support (137152a79a30f9adfb9b6bad0e84dabfb409b97c)
- processing modes (6bf085094efd3da9557dc19945cc362ea3135743 and c69fc3b44e6ed22f64cbfa4775fcbd0ae0de2cd6)

It would be nice to release them and publish to PyPI.

**Comment by sorki** [comment]
Thanks for a reminder, starting looking at EMNIST support from #11, will add that and release everything.

**Comment by jenevans33** [comment]
This is a great utility. Unfortunately PIP Install (PyPi) is lagging behind on a version and so does not support the numpy options passed in.
