### ISSUE TITLE
mnist vs python-mnist

### ISSUE THREAD

**Issue by graingert** [sorki/python-mnist#16]
@datapythonista
@sorki

there's https://pypi.python.org/pypi/mnist/ and https://pypi.python.org/pypi/python-mnist/

Seems like a bit of duplication of effort? How about merging the projects?

**Comment by graingert** [comment]
https://github.com/datapythonista/mnist/issues/6

**Comment by sorki** [comment]
Dunno, looks doable. I've added the reasons why this exists to README recently although it can now optionally use numpy but not for loading data.

> This package doesn't use numpy by design as when I've tried to find a working implementation all of them were based on some archaic version of numpy and none of them worked. This loads data files with struct.unpack instead.

**Comment by sorki** [comment]
I'm just gonna close this and forget about the other package, sorry.
