### ISSUE TITLE
Cannot import MNIST

### ISSUE THREAD

**Issue by Anandh06Kishan** [sorki/python-mnist#18]
`from mnist import MNIST`
when executing this line it shows 

> cannot import name 'MNIST'

**Comment by emeri1md** [comment]
I'm getting the same issue.  Can you please tell us the resolution?

**Comment by emeri1md** [comment]
I had to change it to from mnist.loader import MNIST

That made it work correctly.

**Comment by Ricardo-Fellini4** [comment]
i had change  from mnist.loader import MNIST but it still doesn,t work
