### ISSUE TITLE
Hmmm, GPL... possible to change to BSD2 please?

### ISSUE THREAD

**Issue by hughperkins** [sorki/python-mnist#5]
Hi,

GPL is quite restrictive.  My own libraries are BSD2, not compatiable.  Please can you consider relicensing as BSD2?

**Comment by sorki** [comment]
No problem!

**Comment by hughperkins** [comment]
Thanks! :-)

**Comment by sorki** [comment]
Done.

**Comment by hughperkins** [comment]
Great!  Thank-you Richard.
