### ISSUE TITLE
ReadMe modifications

### ISSUE THREAD

**Issue by kingfengji** [sorki/python-mnist#6]
hi there, great package and thanks for your contribution.

only one tiny suggestion

In the last lines of readme file, perhaps it is better suggesting
**
images, labels = mndata.load_training() # list of images and labels
**

instead of 
**
mndata.load_training() # the first time I run it, my screen went crazy with numbers jumping around.
**
Also comment out the data type of each one.

again, thank you!

**Comment by sorki** [comment]
Thank you!
