### ISSUE TITLE
Permission denied when trying to load training

### ISSUE THREAD

**Issue by StanislavNikitin** [sorki/python-mnist#7]
I am trying to start a program as shown in Getting Started but face with this error:

`Traceback (most recent call last):
  File "C:/Users/Stanislav/Desktop/Master/MLKR/Test.py", line 3, in <module>
    mndata.load_training()

  File "C:\Anaconda2\lib\site-packages\mnist\loader.py", line 33, in load_training
    os.path.join(self.path, self.train_lbl_fname))

  File "C:\Anaconda2\lib\site-packages\mnist\loader.py", line 42, in load
    with open(path_lbl, 'rb') as file:
IOError: [Errno 13] Permission denied: 'data/train-labels-idx1-ubyte'`

**Comment by sorki** [comment]
Are you setting mndata.path  or giving it path when creating MNIST object?

**Comment by StanislavNikitin** [comment]
Just did the same:```

from mnist import MNIST
mndata = MNIST('data')
images, labels = mndata.load_training()
```
where dir data contains  .idx3-ubyte files

After all, I found a solution with replacing 
`self.test_img_fname = 't10k-images-idx3-ubyte'`
with
`self.test_img_fname = 't10k-images.idx3-ubyte'`
in loader.py

**Comment by sorki** [comment]
Ok. Btw  it seems that http://yann.lecun.com/exdb/mnist/ used in get_data.sh is down. Where did you get your data from? I might change that link to something more up to date if original site is dead.

**Comment by sorki** [comment]
Nevermind. It's up again.

**Comment by StanislavNikitin** [comment]
Hello!
Yes, I used this data : http://yann.lecun.com/exdb/mnist/
