### ISSUE TITLE
numpy output?

### ISSUE THREAD

**Issue by stablum** [sorki/python-mnist#9]
Would it make sense to return Numpy arrays? This would be very convenient for me and would speed up the processing modes I added with the pull request. Drawback would be the introduction of an additional library dependency. Anyways, I guess that nowadays every Python developer working with MNIST does have Numpy installed. Numpy could also be imported only on-demand (with an if statement), in order to avoid the mandatory dependency. Thoughts?

**Comment by sorki** [comment]
Yes, sure. You can do try import .. except ImportError to check for numpy. I've created this as pure python unpacker after I've found several numpy mnist unpackers each requiring different numpy version to work.

**Comment by stablum** [comment]
great. I just created pull request #10 that implements this.

**Comment by sorki** [comment]
Merged.

**Comment by stablum** [comment]
great! thanks! :)
